---
title: "Wikipedia Hindi/English Page Exploration"
author: "Molly G Hickman"
date: "9/30/2019"
output: html_document
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
library(WikipediR)
library(pageviews)
library(distill)
library(rmarkdown)
library(dplyr)

start = "2000010112"
end = "2020040112" # April 2020

articles_eng = c("Kashmir conflict", "Article 370 of the Constitution of India", "Insurgency in Jammu and Kashmir", "Jammu and Kashmir Reorganisation Act, 2019", "2019 Pulwama attack")

articles_hin = c("कश्मीर_विवाद", "अनुच्छेद_३७०", "जम्मू_और_कश्मीर_में_विद्रोह", "२०१९_पुलवामा_हमला", "जम्मू_और_कश्मीर_पुनर्गठन_अधिनियम,_2# 019")

articles_ur = c("مسئلہ_کشمیر", 
                "آئین_ہند_کی_دفعہ_370",
                "جموں_و_کشمیر_تنظیم_نو_ایکٹ،_2019ء",
                "پلوامہ_حملہ،_2019ء")

```

## Page Content
Note: Hindi page content query executes fine, but when you try to create the report it errors out

```{r page content}
# English
ekashmir = page_content("en", "wikipedia", page_name = articles_eng[1])
earticle = page_content("en", "wikipedia", page_name = articles_eng[2])
einsurg = page_content("en", "wikipedia", page_name = articles_eng[3])

# Hindi
hkashmir = page_content("hi", "wikipedia", page_name = articles_hin[1])
harticle = page_content("hi", "wikipedia", page_name = articles_hin[2])
hinsurg = page_content("hi", "wikipedia", page_name = articles_hin[3])
                         
```

## Page Views - English

```{r pageviews Kashmir conflict english}
ekash_pv = article_pageviews(start=start, end=end, article=articles_eng[1])

# Subset of columns, for all paginated tables
wantCols = names(ekash_pv) %in% c('project', 'language', 'article', 'date', 'views')
paged_table(ekash_pv[wantCols])
```


```{r pageviews Article 370 english}
e370_pv = article_pageviews(start=start, end=end, article=articles_eng[2])
paged_table(e370_pv[wantCols])
```


```{r pageviews Jammu and Kashmir english}
ejamm_pv = article_pageviews(start=start, end=end, article=articles_eng[3])
paged_table(ejamm_pv[wantCols])
```

```{r pageviews Reorganisation english}
ereorg_pv = article_pageviews(start=start, end=end, article=articles_eng[4])
paged_table(ereorg_pv[wantCols])
```

```{r pageviews Pulwama Attack english}
epulwama_pv = article_pageviews(start=start, end=end, article=articles_eng[5])
paged_table(epulwama_pv[wantCols])
```

```{r merge to one file for output - english}
a <- bind_rows(ekash_pv, e370_pv, ejamm_pv, ereorg_pv, epulwama_pv)
write.csv(a, "wiki_english_pageviews_2000_thru_Mar2020.csv")
```

## Hindi pageviews

```{r pageviews Kashmir conflict hindi}
hkash_pv = article_pageviews(project="hi.wikipedia", start=start, end=end, article=articles_hin[1])
hkash_pv$article <- articles_eng[1] # replace unicode nonsense with article name
paged_table(hkash_pv)
```

```{r pageviews Article 370 hindi}
h370_pv = article_pageviews(project="hi.wikipedia", start=start, end=end, article=articles_hin[2])
h370_pv$article <- articles_eng[2] # replace unicode nonsense with article name
paged_table(h370_pv[wantCols])
```

```{r pageviews Jammu and Kashmir hindi}
hjamm_pv = article_pageviews(project="hi.wikipedia", start=start, end=end, article=articles_hin[3])
hjamm_pv$article <- articles_eng[3] # replace unicode nonsense with article name
paged_table(hjamm_pv[wantCols])
```

```{r pageviews Reorganisation hindi}
hreorg_pv = article_pageviews(start=start, end=end, article=articles_hin[4])
paged_table(hreorg_pv[wantCols])
```

```{r pageviews Pulwama Attack hindi}
hpulwama_pv = article_pageviews(start=start, end=end, article=articles_hin[5])
paged_table(epulwama_pv[wantCols])
```

```{r merge to one file for output - hindi}
b <- bind_rows(hkash_pv, h370_pv, hjamm_pv) #hreorg_pv, hpulwama_pv)
write.csv(b, "wiki_hindi_pageviews_2000_thru_Mar2020.csv")
```

## Urdu pageviews

```{r pageviews Kashmir conflict urdu}
ukash_pv = article_pageviews(project="ur.wikipedia", start=start, end=end, article=articles_ur[1])
ukash_pv$article <- articles_eng[1] # replace unicode nonsense with article name
paged_table(ukash_pv)
```

```{r pageviews Article 370 hindi}
u370_pv = article_pageviews(project="ur.wikipedia", start=start, end=end, article=articles_ur[2])
u370_pv$article <- articles_eng[2] # replace unicode nonsense with article name
paged_table(u370_pv[wantCols])
```

```{r merge to one file for output - hindi}
b <- bind_rows(ukash_pv, u370_pv) # no insurgency article
write.csv(b, "wiki_urdu_pageviews_2000_thru_Mar2020.csv")
```

